<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageFloatingVersionsEnabled>true</CentralPackageFloatingVersionsEnabled>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Mermaider" Version="0.12.1" />
    <PackageVersion Include="Microsoft.SourceLink.GitHub" Version="10.0.203" />
    <PackageVersion Include="JetBrains.Annotations" Version="2025.2.4" />
    <PackageVersion Include="Novolis.IO.Paths" Version="2026.1.*" />
    <PackageVersion Include="Novolis.Documents" Version="2026.1.*" />
    <PackageVersion Include="Novolis.Documents.Layout" Version="2026.1.*" />
    <PackageVersion Include="Novolis.Documents.Skia" Version="2026.1.*" />
    <PackageVersion Include="Novolis.Math.Measure" Version="2026.1.*" />
    <PackageVersion Include="SkiaSharp" Version="3.116.1" />
    <PackageVersion Include="SkiaSharp.NativeAssets.Win32" Version="3.116.1" />
    <PackageVersion Include="SkiaSharp.NativeAssets.Linux" Version="3.116.1" />
    <PackageVersion Include="SkiaSharp.NativeAssets.macOS" Version="3.116.1" />
    <PackageVersion Include="Svg.Skia" Version="3.7.0" />
    <PackageVersion Include="TUnit" Version="1.44.39" />
    <PackageVersion Include="YamlDotNet" Version="16.3.0" />

  </ItemGroup>
</Project>
