<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <PackageId>Novolis.Markup.Html</PackageId>
    <IsPackable>true</IsPackable>
    <RootNamespace>Novolis.Markup.Html</RootNamespace>
    <Description>Fluent HTML, CSS, JavaScript (functions/classes), and SVG builders for .NET.</Description>
    <PackageTags>html;css;javascript;svg;fluent;markup;novolis</PackageTags>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>
  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="\" />
  </ItemGroup>
</Project>
